name: CD Single
run-name: 'Manual Deploy ${{ github.event.inputs.service }} - ${{ github.event.inputs.environment }} (${{ github.event.inputs.version }})'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      environment:
        description: 'Environment'
        type: choice
        required: true
        default: 'test'
        options: ['test', 'stg', 'prd']
      service:
        description: 'Service'
        type: choice
        required: true
        default: 'municipality'
        options: ['municipality', 'streetname', 'postal', 'address', 'building', 'parcel']


permissions:
  id-token: write

jobs:
  deployment:
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.1.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      service-name: 'cache'
      application: 'cache'
      version: ${{ github.event.inputs.version }}
      domain: ${{ github.event.inputs.service }}
      project: 'grawr'
      use-subfolder: true
    secrets: inherit
