name: CD Single

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      environment:
        description: 'Environment'
        type: choice
        required: true
        default: 'tst'
        options: ['tst', 'stg', 'prd']
      service:
        description: 'Service'
        type: choice
        required: true
        default: 'municipality-cache'
        options: ['municipality-cache', 'streetname-cache', 'postal-cache', 'address-cache', 'building-cache', 'parcel-cache']

jobs:
  deployment:
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      service-name: ${{ github.event.inputs.service }}
      version: ${{ github.event.inputs.version }}
      domain: 'basisregisters'
      project: 'basisregisters'
    secrets: inherit
